services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: pantry
      POSTGRES_USER: pantry
      POSTGRES_PASSWORD: pantry
    ports:
      - "55432:5432"
    volumes:
      - pantry_postgresql:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "55672:5672"
      - "15672:15672"
    volumes:
      - pantry_rabbitmq:/var/lib/rabbitmq/mnesia

  nginx:
    image: nginx:alpine
    ports:
      - "8088:80"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pantry_postgresql:
  pantry_rabbitmq:
