name: Master Deployment

on:
  workflow_call:
  workflow_dispatch:

jobs:
  detect-changes:
    name: Detect Changes for Deployments
    uses: ./.github/workflows/DetectChanges.yml

  migrate:
    name: Deploy Migrator
    needs: [detect-changes]
    if: ${{ needs.detect-changes.outputs.migrate == 'true' && !failure() && !cancelled() }}
    uses: ./.github/workflows/DeployMigrator.yml
    secrets: inherit

  deploy_telegram_bot:
    name: Deploy TelegramBot
    needs: [detect-changes, migrate]
    if: ${{ needs.detect-changes.outputs.backend == 'true' && !failure() && !cancelled() }}
    uses: ./.github/workflows/DeployTelegramBot.yml
    secrets: inherit

  deploy_frontend:
    name: Deploy Frontend
    needs: [detect-changes]
    if: ${{ needs.detect-changes.outputs.frontend == 'true' && !failure() && !cancelled() }}
    uses: ./.github/workflows/DeployFrontend.yml
    secrets: inherit

  deploy_nginx:
    name: Deploy Nginx
    needs: [detect-changes]
    if: ${{ needs.detect-changes.outputs.nginx == 'true' && !failure() && !cancelled() }}
    uses: ./.github/workflows/DeployNginx.yml
    secrets: inherit
